<?php

$labels = array();
$labels['settings']					= 'CardDAV Einstellungen';
$labels['settings_tab']				= 'CardDAV';
$labels['settings_label']			= 'Label';

$messages = array();
$messages['settings_empty_values']	= 'Bitte f&uuml;lle alle Felder aus';
$messages['settings_saved']			= 'CardDAV-Server Einstellungen erfolgreich gespeichert';
$messages['settings_save_failed']	= 'Beim Speichern der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_deleted']		= 'CardDAV-Server Einstellungen erfolgreich gelöscht';
$messages['settings_delete_failed']	= 'Beim Löschen der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_no_connection']	= 'Konnte keine Verbindung zum cardDAV-Server aufbauen';
