<?php

$labels = array();
$labels['settings']						= 'CardDAV Einstellungen';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Label';
$labels['addressbook_contacts']			= 'CardDAV-Kontakte';
$labels['addressbook_sync']				= 'Adressbuch synchronisieren';

$messages = array();
$messages['settings_empty_values']		= 'Bitte f&uuml;lle alle Felder aus';
$messages['settings_saved']				= 'CardDAV-Server Einstellungen und vCards erfolgreich gespeichert';
$messages['settings_save_failed']		= 'Beim Speichern der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_delete_loading']	= 'L&ouml;sche CardDAV-Server Einstellungen und dazugeh&ouml;rige lokale Kontakte';
$messages['settings_deleted']			= 'CardDAV-Server Einstellungen erfolgreich gel&ouml;scht';
$messages['settings_delete_failed']		= 'Beim L&ouml;schen der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_no_connection']		= 'Konnte keine Verbindung zum CardDAV-Server aufbauen';
$messages['settings_init_server']		= 'Überpr&uuml;fe die Verbindung zum CardDAV-Server und importiere vCards';