<?php

$labels = array();
$labels['settings']						= 'CardDAV-Einstellungen';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Label';
$labels['settings_read_only']			= 'Nur Lesezugriff';
$labels['settings_curl_not_installed']	= 'Die PHP-Erweiterung CURL ist nicht installiert. Bitte installiere CURL um das CardDAV-Plugin nutzen zu k&ouml;nnen.';
$labels['addressbook_contacts']			= 'CardDAV-Kontakte';
$labels['addressbook_sync']				= 'CardDAV-Adressbuch synchronisieren';

$messages = array();
$messages['settings_empty_values']		= 'Bitte gebe ein Label und die URL an';
$messages['settings_saved']				= 'CardDAV-Server Einstellungen und vCards erfolgreich gespeichert';
$messages['settings_save_failed']		= 'Beim Speichern der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_delete_loading']	= 'L&ouml;sche CardDAV-Server Einstellungen und dazugeh&ouml;rige lokale Kontakte';
$messages['settings_deleted']			= 'CardDAV-Server Einstellungen erfolgreich gel&ouml;scht';
$messages['settings_delete_failed']		= 'Beim L&ouml;schen der CardDAV-Server Einstellungen ist ein Fehler aufgetreten';
$messages['settings_no_connection']		= 'Konnte keine Verbindung zum CardDAV-Server aufbauen';
$messages['settings_init_server']		= 'Überpr&uuml;fe die Verbindung zum CardDAV-Server und importiere vCards';
$messages['addressbook_synced']			= 'CardDAV-Kontakte erfolgreich synchronisiert';
$messages['addressbook_sync_failed']	= 'Bei der Synchronisierung der CardDAV-Kontakte ist ein Fehler aufgetreten';
$messages['addressbook_sync_loading']	= 'Synchronisiere CardDAV-Kontakte';