<?php

$labels = array();
$labels['settings']					= 'CardDAV settings';
$labels['settings_tab']				= 'CardDAV';
$labels['settings_label']			= 'Label';

$messages = array();
$messages['settings_empty_values']	= 'Please fill out all fields';
$messages['settings_saved']			= 'CardDAV-Server settings saved';
$messages['settings_save_failed']	= 'Failed to save CardDAV-Server settings';
$messages['settings_deleted']		= 'CardDAV-Server settings deleted';
$messages['settings_delete_failed']	= 'Failed to delete cardDAV-Server settings';
$messages['settings_no_connection']	= 'Can\'t connect to the cardDAV-Server';
