<?php

$labels = array();
$labels['settings']						= 'CardDAV settings';
$labels['settings_server']				= 'CardDAV server';
$labels['settings_server_form']			= 'Add your CardDAV server';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Label';
$labels['settings_read_only']			= 'Read only';
$labels['settings_curl_not_installed']	= 'The PHP extension CURL is not installed! Please install CURL to use the CardDAV plugin.';
$labels['addressbook_contacts']			= 'CardDAV contacts';
$labels['addressbook_sync']				= 'Synchronize CardDAV addressbook';

$messages = array();
$messages['settings_empty_values']		= 'Please fill out all Label and URL';
$messages['settings_saved']				= 'CardDAV server settings and vCards saved';
$messages['settings_save_failed']		= 'Failed to save CardDAV server settings';
$messages['settings_delete_loading']	= 'Delete CardDAV server settings and related local contacts';
$messages['settings_deleted']			= 'CardDAV server settings deleted';
$messages['settings_delete_failed']		= 'Failed to delete CardDAV server settings';
$messages['settings_no_connection']		= 'Can\'t connect to the CardDAV server';
$messages['settings_init_server']		= 'Checking CardDAV server connection and import vCards';
$messages['addressbook_synced']			= 'CardDAV contacts synchronized';
$messages['addressbook_sync_failed']	= 'An error occurred while synchronizing the CardDAV contacts';
$messages['addressbook_sync_loading']	= 'Synchronize CardDAV contacts';