<?php

$labels = array();
$labels['settings']						= 'Configuración CardDAV';
$labels['settings_server']				= 'Servidor CardDAV';
$labels['settings_server_form']			= 'Añadir un servidor CardDAV';
$labels['settings_example_server_list']	= 'URL de ejemplo del servidor CardDAV';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Etiqueta';
$labels['settings_read_only']			= 'Sólo Lectura';
$labels['settings_curl_not_installed']	= 'The PHP extension CURL is not installed! Please install CURL to use the CardDAV plugin.';
$labels['addressbook_contacts']			= 'Contactos CardDAV';
$labels['addressbook_sync']				= 'Sincronizar libreta de direcciones CardDAV';

$messages = array();
$messages['settings_empty_values']		= 'Rellena la Etiqueta y la URL';
$messages['settings_saved']				= 'Configuración del servidor CardDAV guardada';
$messages['settings_save_failed']		= 'Error guardando la configuración del servidor CardDAV';
$messages['settings_delete_loading']	= 'Borrar la configuración del servidor CardDAV y los contactos asociados';
$messages['settings_deleted']			= 'Configuración del servidor CardDAV eliminada';
$messages['settings_delete_failed']		= 'Error borrando la configuración del servidor CardDAV';
$messages['settings_no_connection']		= 'Error conectando con el servidor CardDAV';
$messages['settings_init_server']		= 'Sincronizando la libreta de direcciones con el servidor CardDAV';
$messages['addressbook_synced']			= 'Libreta de direcciones CardDAV sincronizada';
$messages['addressbook_sync_failed']	= 'Error sincronizando la libreta de direcciones CardDAV';
$messages['addressbook_sync_loading']	= 'Sincronizar libreta de direcciones CardDAV';
