<?php

$labels = array();
$labels['settings']						= 'CardDAV-Settings';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Label';
$labels['addressbook_contacts']			= 'CardDAV-Contacts';
$labels['addressbook_sync']				= 'Synchronise CardDAV-Addressbook';

$messages = array();
$messages['settings_empty_values']		= 'Introduisez un nom et l\'URL de votre CardDav';
$messages['settings_saved']				= 'Les paramètres CardDAV-Server et vCards sauvergardés';
$messages['settings_save_failed']		= 'Echec de la sauvagarde des paramètres CardDAV-Server';
$messages['settings_delete_loading']	= 'Effacer les paramètres CardDAV-Server et les contacts du serveur local';
$messages['settings_deleted']			= 'Paramètres CardDAV-Server effacés';
$messages['settings_delete_failed']		= 'Impossible d\'effacer les paramètres CardDAV-Server';
$messages['settings_no_connection']		= 'Connexion au CardDAV-Server impossible';
$messages['settings_init_server']		= 'Vérification de la connexion au CardDAV-Server et importation des adresses vCards';
$messages['addressbook_synced']			= 'CardDAV-Contacts synchronisés';
$messages['addressbook_sync_failed']	= 'Une erreur s\'est produite lors de la synchronisation avec CardDAV-Contacts';
$messages['addressbook_sync_loading']	= 'Synchronisation CardDAV-Contacts';
