<?php

$labels = array();
$labels['settings']						= 'Impostazioni CardDAV';
$labels['settings_tab']					= 'CardDAV';
$labels['settings_label']				= 'Descrizione';
$labels['addressbook_contacts']			= 'Contatti CardDAV';
$labels['addressbook_sync']				= 'Sincronizza la rubrica CardDAV';

$messages = array();
$messages['settings_empty_values']		= 'Per favore, completa tutti i campi';
$messages['settings_saved']				= 'Impostazioni del server CardDAV e vCard salvati';
$messages['settings_save_failed']		= 'Errore durante il salvataggio delle impostazioni del server CardDAV';
$messages['settings_delete_loading']	= 'Elimina le impostazioni del server CardDAV e i contatti locali corrispondenti';
$messages['settings_deleted']			= 'Impostazioni del server CardDAV eliminate';
$messages['settings_delete_failed']		= 'Errore durante l\'eliminazione delle impostazioni del server CardDAV';
$messages['settings_no_connection']		= 'Impossibile connettersi al server CardDAV';
$messages['settings_init_server']		= 'Verifica della connessione al server CardDAV e importazione delle vCard';
$messages['addressbook_synced']			= 'Contatti CardDAV sincronizzati';
$messages['addressbook_sync_failed']	= 'Errore durante la sincronizzazione dei contatti CardDAV';
$messages['addressbook_sync_loading']	= 'Sincronizzazione dei contatti CardDAV';