<?php

$labels = array();
$labels['settings']                     = 'Ustawienia CardDAV';
$labels['settings_server']              = 'Serwer CardDAV';
$labels['settings_server_form']         = 'Dodaj serwer CardDAV';
$labels['settings_example_server_list'] = 'Przykładowe URL\'e CardDAV';
$labels['settings_tab']                 = 'CardDAV';
$labels['settings_label']               = 'Nazwa Wpisu';
$labels['settings_read_only']           = 'Tylko odczyt';
$labels['settings_curl_not_installed']  = 'Roszerzenie CURL do PHP nie jest zainstalowane! Zainstaluj CURL\'a i spróbuj użyć pluginu CardDAV ponownie';
$labels['addressbook_contacts']         = 'Kontakty CardDAV';
$labels['addressbook_sync']             = 'Synchronizuj książki adresowe CardDAV';

$messages = array();
$messages['settings_empty_values']      = 'Proszę wypełnić wszystkie pola';
$messages['settings_saved']             = 'Ustawienia konta CardDAV zapisano';
$messages['settings_save_failed']       = 'Nie udało się zapisać ustawień CardDAV';
$messages['settings_delete_loading']    = 'Usuń ustawienia konta CardDAV';
$messages['settings_deleted']           = 'Ustawienia konta CardDAV usunięto';
$messages['settings_delete_failed']     = 'Nie udało się usunąć konta CardDAV';
$messages['settings_no_connection']     = 'Nie udało się połączyć do serwera CardDAV';
$messages['settings_init_server']       = 'Sprawdzanie połączenia do serwera CardDAV i importowanie kontaktów';
$messages['addressbook_synced']         = 'Kontakty CardDAV pomyślnie zsynchronizowano';
$messages['addressbook_sync_failed']    = 'Wystąpił błąd podczas synchronizowania kontaktów CardDAV';
$messages['addressbook_sync_loading']   = 'Synchronizowanie kontaktów CardDAV';
